
import { DM_Sans, Manrope} from "next/font/google";
import "./globals.css";
import HeaderComponent from "../Modules/Header.jsx";
import FooterComponent from "../Modules/Footer.jsx"
import NextTopLoader from 'nextjs-toploader';
import { Toaster } from "sonner";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"]
})

const manRope = Manrope({
  variable: "--font-man-rope",
  subsets: ["latin"]
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
       className={`antialiased ${dmSans.variable} ${manRope.variable}`}
      >
        <NextTopLoader   color="#B4DD13"
        initialPosition={0.08}
        crawlSpeed={200}
        height={3}
        crawl={true}
        showSpinner={false}
        easing="ease"
        speed={200}
        zIndex={1600}
        showAtBottom={false} />
        <HeaderComponent/>
       <main className="flex-1">{children}</main> 
       <Toaster className="bg-[#B4DD13] text-white"/>
       <FooterComponent/>
      </body>
    </html>
  );
}
